"""
AI Insights — the AI tab visible to all roles.

Three sub-tabs:
  • 📈 Demand Forecast  — per-product chart of actuals vs fitted vs forecast
  • 💰 Price Prediction  — per-product chart of predicted vs actual price + MAPE bar
  • 🎯 Recommendations  — suggests products to buy/stock

All predictions are generated by self-learning models that:
  1. Log every prediction to ai_prediction_log
  2. Backfill actual_value when the truth arrives (order placed / price changed)
  3. Compute MAE/MAPE per product → ai_model_metrics
  4. Bias-correct the next prediction using the learned bias

So the longer the platform runs, the more accurate the predictions get.
The accuracy numbers shown here come from real scored predictions, not
from in-sample fit.

No HTML is used on this page — every visual is a native Streamlit
component (st.line_chart, st.bar_chart, st.dataframe, st.metric,
st.container(border=True)).
"""
from __future__ import annotations

import streamlit as st
import pandas as pd

from auth.session import get_current_user, get_current_role
from utils.ui import page_header, metric_card
from utils.helpers import format_currency
from ai.engine import get_training_summary, MLEngine
from ai.price_prediction import predict_optimal_prices, save_price_predictions_to_supabase
from ai.demand_forecast import forecast_all_products, save_demand_forecasts_to_supabase
from ai.recommendations import get_recommendations


def render_ai_insights():
    page_header("🤖 AI Insights", "Self-learning predictions trained live on your Supabase data")

    user = get_current_user()
    if not user:
        return

    # ---- Check if ML libraries are available ----
    try:
        summary = get_training_summary()
    except Exception as e:
        st.error(f"Failed to load AI engine: {e}")
        return

    if not summary.get("ml_available", True):
        st.warning("⚠️ AI features require additional libraries that aren't installed.")
        st.info(
            "**To enable AI Insights:**\n\n"
            "Add these to your `requirements.txt` on Streamlit Cloud:\n"
            "```\npandas\nnumpy\nscikit-learn\n```\n\n"
            "Then reboot the app. The AI features are optional — everything else works without them."
        )
        return

    _render_model_status(summary)

    # ---- Sub-tabs ----
    sub_tab1, sub_tab2, sub_tab3 = st.tabs([
        "📈 Demand Forecast",
        "💰 Price Prediction",
        "🎯 Recommendations",
    ])

    with sub_tab1:
        _render_demand_forecast()
    with sub_tab2:
        _render_price_prediction()
    with sub_tab3:
        _render_recommendations(user["id"])


def _render_model_status(summary: dict):
    """Show the training data + model metrics — proof the engine is self-learning."""
    st.markdown("##### 🧠 Model Status")

    col1, col2, col3, col4, col5 = st.columns(5)
    with col1:
        metric_card("Training Samples", f"{summary['orders_count']} orders / {summary['order_items_count']} items")
    with col2:
        metric_card("Products Trained", str(summary["products_count"]))
    with col3:
        metric_card("Demand Models", str(summary["demand_models_trained"]))
    with col4:
        r2 = summary.get("price_model_r2", 0)
        metric_card(
            "Price Model R²",
            f"{r2:.2f}",
            delta="✅ trained" if summary.get("price_model_trained") else "❌ no data",
        )
    with col5:
        metric_card(
            "Recommender",
            f"{summary.get('recommender_interactions', 0)} interactions",
            delta="✅ ready" if summary.get("recommender_trained") else "⚠️ needs data",
        )

    # ---- Self-learning loop status ----
    st.markdown("##### 🔁 Self-Learning Loop")
    sc1, sc2, sc3, sc4 = st.columns(4)
    with sc1:
        metric_card("Predictions Logged", str(summary.get("total_predictions_logged", 0)))
    with sc2:
        metric_card("Scored vs Actuals", str(summary.get("scored_predictions", 0)))
    with sc3:
        demand_acc = summary.get("demand_accuracy_pct")
        metric_card(
            "Demand Accuracy",
            f"{demand_acc:.1f}%" if isinstance(demand_acc, (int, float)) else "—",
            delta="📈 learning" if summary.get("scored_predictions", 0) > 0 else "⏳ needs scored data",
        )
    with sc4:
        price_acc = summary.get("price_accuracy_pct")
        metric_card(
            "Price Accuracy",
            f"{price_acc:.1f}%" if isinstance(price_acc, (int, float)) else "—",
            delta="📈 learning" if summary.get("scored_predictions", 0) > 0 else "⏳ needs scored data",
        )

    st.caption(
        "🔄 Models auto-retrain every 5 minutes. Every prediction is logged to "
        "`ai_prediction_log`, and once the truth arrives (an order is placed or a "
        "price is changed) the engine backfills the actual value, computes MAE/MAPE "
        "per product, and uses the learned bias to correct the next prediction. "
        f"Last trained: {summary.get('last_trained', 'unknown')[:19]} · "
        f"Model version: {summary.get('model_version', 'unknown')}"
    )
    st.markdown("---")


def _render_demand_forecast():
    st.markdown("##### 📈 Demand Forecast — Next 30 Days")
    st.caption("Predicts total demand per product over the next 30 days. Pick a product to see its actuals-vs-forecast chart.")

    try:
        forecasts = forecast_all_products(horizon_days=30)
    except Exception as e:
        st.error(f"Failed: {e}")
        return

    if not forecasts:
        st.info("No products to forecast yet.")
        return

    trained = [f for f in forecasts if f.get("method") in ("linear_regression", "gradient_boosting")]
    if not trained:
        st.warning(
            "⚠️ Not enough order history yet to train demand models. "
            "Place a few orders first, then check back — the model retrains every 5 minutes."
        )

    # Save to Supabase (background)
    if trained and st.button("💾 Save predictions to database", key="save_demand"):
        n = save_demand_forecasts_to_supabase(trained)
        st.success(f"Saved {n} demand predictions to ai_predictions table.")

    # ---- Per-product line chart ----
    if trained:
        st.markdown("##### 📊 Per-Product Demand Chart")
        product_options = {f"{f.get('name', '')} ({f.get('sku', '')})": f for f in trained}
        selected_label = st.selectbox(
            "Select a product",
            options=list(product_options.keys()),
            key="demand_product_select",
        )
        selected = product_options.get(selected_label)
        if selected:
            _render_demand_chart(selected)

    # ---- Full table ----
    st.markdown("##### 📋 All Products")
    df = pd.DataFrame([
        {
            "SKU": f.get("sku", ""),
            "Product": f.get("name", ""),
            "Category": f.get("category", ""),
            "Current Stock": f.get("current_stock", 0),
            "Predicted Demand (30d)": f.get("predicted_demand_30d", 0),
            "Avg Daily": f.get("avg_daily_demand", 0),
            "Trend": f.get("trend", ""),
            "Confidence": f"{f.get('confidence', 0) * 100:.0f}%",
            # Look up the accuracy from THIS row's forecast dict, not
            # from the "selected" product — that variable only exists
            # inside the per-product chart branch above and is
            # undefined here when there are no trained forecasts.
            "Accuracy (MAPE)": _format_mape(f.get("accuracy")),
            "Samples": f.get("samples", 0),
            "Method": f.get("method", ""),
        }
        for f in forecasts
    ])
    st.dataframe(df, use_container_width=True, hide_index=True)

    # ---- Restock alerts ----
    st.markdown("##### ⚠️ Restock Alerts")
    alerts = [
        f for f in forecasts
        if f.get("predicted_demand_30d", 0) > f.get("current_stock", 0)
        and f.get("method") in ("linear_regression", "gradient_boosting")
    ]
    if not alerts:
        st.success("All products have sufficient stock for predicted demand.")
    else:
        for a in alerts:
            shortfall = a["predicted_demand_30d"] - a["current_stock"]
            st.warning(
                f"**{a['name']}** ({a['sku']}) — predicted demand {a['predicted_demand_30d']:.0f} "
                f"exceeds stock {a['current_stock']}. Restock by ~{shortfall:.0f} units."
            )


def _render_demand_chart(forecast: dict):
    """Plot actuals vs fitted (history) + forecast (future) for one product.

    Uses st.line_chart with a 3-column DataFrame:
      date | Actual | Fitted | Forecast
    """
    history = forecast.get("history", []) or []
    future = forecast.get("forecast", []) or []

    rows = []
    for h in history:
        rows.append({
            "Date": h["date"],
            "Actual": float(h.get("actual", 0)),
            "Fitted (model)": float(h.get("fitted", 0)) if h.get("fitted") is not None else None,
            "Forecast": None,
        })
    for f in future:
        rows.append({
            "Date": f["date"],
            "Actual": None,
            "Fitted (model)": None,
            "Forecast": float(f.get("predicted", 0)),
        })

    if not rows:
        st.info("No historical data yet for this product — place some orders to see the chart.")
        return

    chart_df = pd.DataFrame(rows).set_index("Date")
    # Convert date strings to datetime so the x-axis is ordered correctly.
    chart_df.index = pd.to_datetime(chart_df.index)
    chart_df = chart_df.sort_index()

    # Stash the description in a small caption row above the chart.
    acc = forecast.get("accuracy")
    cap_parts = [
        f"Trend: **{forecast.get('trend', 'stable')}**",
        f"Predicted 30-day demand: **{forecast.get('predicted_demand_30d', 0):.0f} units**",
        f"Confidence: **{forecast.get('confidence', 0) * 100:.0f}%**",
        f"Method: `{forecast.get('method', '?')}`",
    ]
    if acc:
        mape = acc.get("mape")
        if mape is not None:
            cap_parts.append(f"Historical accuracy: **{100 - mape:.1f}%** (MAPE {mape:.1f}%)")
        cap_parts.append(f"Samples scored: **{acc.get('samples', 0)}**")
    st.caption(" · ".join(cap_parts))

    st.line_chart(chart_df, use_container_width=True, height=320)


def _render_price_prediction():
    st.markdown("##### 💰 Price Optimization")
    st.caption("Suggests optimal prices based on stock levels, category, and sales velocity. Pick a product to see its predicted-vs-actual price history.")

    try:
        predictions = predict_optimal_prices()
    except Exception as e:
        st.error(f"Failed: {e}")
        return

    if not predictions:
        st.info("Not enough product data to train the price model yet.")
        return

    if st.button("💾 Save predictions to database", key="save_prices"):
        n = save_price_predictions_to_supabase(predictions)
        st.success(f"Saved {n} price predictions.")

    # ---- Per-product chart ----
    st.markdown("##### 📊 Per-Product Price Accuracy")
    product_options = {f"{p['name']} ({p['sku']})": p for p in predictions}
    selected_label = st.selectbox(
        "Select a product",
        options=list(product_options.keys()),
        key="price_product_select",
    )
    selected_p = product_options.get(selected_label)
    if selected_p:
        _render_price_chart(selected_p)

    # ---- MAPE bar chart across all products ----
    st.markdown("##### 📉 Price Accuracy Across All Products (MAPE %, lower is better)")
    mape_rows = []
    for p in predictions:
        acc = p.get("accuracy")
        mape = (acc or {}).get("mape")
        if mape is not None:
            mape_rows.append({"Product": p["name"], "MAPE %": float(mape)})
    if mape_rows:
        mape_df = pd.DataFrame(mape_rows).set_index("Product")
        st.bar_chart(mape_df, use_container_width=True, height=280)
    else:
        st.info("No scored price predictions yet. As producers change prices in response to recommendations, accuracy will appear here.")

    # ---- Full table ----
    st.markdown("##### 📋 All Products")
    df = pd.DataFrame([
        {
            "SKU": p["sku"],
            "Product": p["name"],
            "Current Price": format_currency(p["current_price"]),
            "Predicted Price": format_currency(p["predicted_price"]),
            "Difference": format_currency(p["difference"]),
            "% Change": f"{p['pct_change']:+.1f}%",
            "Recommendation": p["recommendation"].upper(),
            "Confidence": f"{p['confidence'] * 100:.0f}%",
            "Accuracy (MAPE)": _format_mape(p.get("accuracy")),
        }
        for p in predictions
    ])
    st.dataframe(df, use_container_width=True, hide_index=True)

    # ---- Summary ----
    st.markdown("##### 💡 Quick Recommendations")
    increase = [p for p in predictions if p["recommendation"] == "increase"]
    decrease = [p for p in predictions if p["recommendation"] == "decrease"]
    hold = [p for p in predictions if p["recommendation"] == "hold"]

    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("📈 Increase Price", len(increase))
    with col2:
        st.metric("📉 Decrease Price", len(decrease))
    with col3:
        st.metric("➡️ Hold Price", len(hold))


def _render_price_chart(prediction: dict):
    """Plot predicted vs actual price over time for one product.

    Uses st.line_chart with a 3-column DataFrame:
      date | Predicted | Actual
    """
    history = prediction.get("history", []) or []
    if not history:
        st.info("No scored price predictions yet for this product. Once the producer changes the price, the actual line will appear here.")
        return

    rows = []
    for h in history:
        rows.append({
            "Date": h.get("predicted_at", ""),
            "Predicted (Br)": h.get("predicted"),
            "Actual (Br)": h.get("actual"),
        })

    chart_df = pd.DataFrame(rows).set_index("Date")
    chart_df.index = pd.to_datetime(chart_df.index, errors="coerce")
    chart_df = chart_df.sort_index()

    cap_parts = [
        f"Current price: **{format_currency(prediction['current_price'])}**",
        f"Predicted optimal: **{format_currency(prediction['predicted_price'])}**",
        f"Recommendation: **{prediction['recommendation'].upper()}** ({prediction['pct_change']:+.1f}%)",
        f"Bias correction applied: **{prediction.get('bias', 0):.2f}**",
    ]
    acc = prediction.get("accuracy")
    if acc:
        mape = acc.get("mape")
        if mape is not None:
            cap_parts.append(f"Accuracy: **{100 - mape:.1f}%** (MAPE {mape:.1f}%)")
        cap_parts.append(f"Samples scored: **{acc.get('samples', 0)}**")
    st.caption(" · ".join(cap_parts))

    st.line_chart(chart_df, use_container_width=True, height=320)


def _render_recommendations(user_id: str):
    st.markdown("##### 🎯 Personalized Recommendations")
    st.caption("Collaborative filtering — suggests products based on what similar users order/favorite.")

    try:
        recs = get_recommendations(user_id, top_n=6)
    except Exception as e:
        st.error(f"Failed: {e}")
        return

    if not recs:
        st.info("No recommendations available yet.")
        return

    method_label = {
        "collaborative_filtering": "🎯 Based on users with similar taste",
        "popularity_based": "🔥 Most popular products",
        "fallback_random": "✨ Try these products",
    }.get(recs[0].get("method", ""), "Recommended")

    st.info(method_label)

    cols = st.columns(3)
    for i, r in enumerate(recs):
        with cols[i % 3]:
            with st.container(border=True):
                if r.get("image_url"):
                    try:
                        st.image(r["image_url"], use_container_width=True)
                    except Exception:
                        st.markdown("📦")
                else:
                    # Native Streamlit placeholder — no HTML.
                    st.container(height=120, border=True).markdown(
                        "📦\n\n*No image*"
                    )
                st.markdown(f"**{r['name']}**")
                st.caption(f"{r.get('category', '')}")
                st.markdown(f"**{format_currency(r['price'])}**")
                st.caption(f"Stock: {r.get('stock', 0)}")


def _format_mape(acc) -> str:
    """Format an accuracy dict as a human-readable MAPE cell."""
    if not acc:
        return "—"
    mape = acc.get("mape")
    if mape is None:
        return "—"
    return f"{mape:.1f}%"
