"""
AI Insights — the AI tab visible to all roles.

Three sub-tabs:
  • 📈 Demand Forecast  — per-product chart of actuals vs fitted vs forecast
  • 💰 Price Prediction  — per-product chart of predicted vs actual price
  • 🎯 Recommendations  — suggests products to buy/stock

All predictions are generated by self-learning models. The platform-wide
internal stats (training counts, MAPE charts, self-learning loop status)
have been moved to the admin dashboard only — they are operational
diagnostics, not user-facing features.

The accuracy numbers shown in per-product charts come from real scored
predictions on the current user's data, not from in-sample fit.

No HTML is used on this page — every visual is a native Streamlit
component (st.line_chart, st.bar_chart, st.dataframe, st.metric,
st.container(border=True)).
"""
from __future__ import annotations

import streamlit as st
import pandas as pd

from auth.session import get_current_user, get_current_role
from utils.ui import page_header
from utils.helpers import format_currency
from ai.engine import get_training_summary, MLEngine
from ai.price_prediction import predict_optimal_prices, save_price_predictions_to_supabase
from ai.demand_forecast import forecast_all_products, save_demand_forecasts_to_supabase
from ai.recommendations import get_recommendations


# ----------------------------------------------------------------------------
# ADMIN-ONLY: model status + self-learning loop stats
# ----------------------------------------------------------------------------
# These are the operational diagnostics for the ML engine. They have been
# moved out of the public AI Insights page (visible to all roles) and into
# the admin dashboard, because:
#   • Training counts, prediction_log row counts, and global MAPE are
#     platform-wide operational metrics, not user-facing features.
#   • The "self-learning loop" status is internal to the engine.
#   • Showing them to non-admins created noise on a page whose purpose
#     is to show *this user's* product forecasts and recommendations.
#
# This function is exported so the admin dashboard can render the same
# panel without code duplication. It is ALSO used here, but ONLY when
# the current user is an admin — non-admins never see this content.
#
# Design: matches the admin dashboard's existing dash-card pattern
# (green-gradient header + grid of metric-box children) for visual
# consistency. The CSS is embedded in the function output so the panel
# is self-contained — it renders correctly on any page without the
# caller having to define a CARD_CSS variable.
# ----------------------------------------------------------------------------

# Card CSS — same design tokens as pages/admin/dashboard.py, but scoped
# to a unique class prefix so it doesn't clash with the admin dashboard's
# own CSS if both are loaded on the same page.
_MODEL_STATUS_CSS = """
<style>
.ais-card {
    background: #ffffff;
    border-radius: 16px;
    overflow: hidden;
    box-shadow: 0 2px 8px rgba(0,0,0,0.08);
    margin-bottom: 20px;
}
.ais-card-header {
    background: linear-gradient(135deg, #1a5c2e 0%, #2d8a4e 100%);
    padding: 20px 24px 18px;
    display: flex;
    align-items: center;
    gap: 14px;
}
.ais-card-header-icon {
    font-size: 2rem;
    line-height: 1;
}
.ais-card-header-text h3 {
    margin: 0;
    color: #ffffff;
    font-size: 1.35rem;
    font-weight: 700;
    letter-spacing: -0.3px;
}
.ais-card-header-text p {
    margin: 2px 0 0;
    color: #a8d5b5;
    font-size: 0.82rem;
}
.ais-card-body {
    padding: 18px 20px;
}
.ais-metric-grid {
    display: flex;
    flex-wrap: wrap;
    gap: 12px;
}
.ais-metric-box {
    flex: 1 1 130px;
    background: #f7f9f7;
    border: 1px solid #e4ece6;
    border-radius: 12px;
    padding: 14px 16px;
    text-align: center;
    min-width: 110px;
}
.ais-metric-box .ais-metric-value {
    font-size: 1.8rem;
    font-weight: 800;
    color: #1a5c2e;
    line-height: 1.1;
}
.ais-metric-box .ais-metric-label {
    font-size: 0.7rem;
    font-weight: 600;
    letter-spacing: 0.06em;
    text-transform: uppercase;
    color: #6b8f72;
    margin-top: 4px;
}
.ais-metric-box .ais-metric-label-icon {
    margin-right: 4px;
}
.ais-metric-box.alert .ais-metric-value { color: #b85c00; }
.ais-metric-box.alert { background: #fff8f0; border-color: #f5d5b0; }
.ais-metric-box.amber .ais-metric-value { color: #b85c00; }
.ais-metric-box.amber { background: #fff8f0; border-color: #f5d5b0; }
.ais-metric-box.success .ais-metric-value { color: #1a5c2e; }
</style>
"""


def _ais_metric_box(value: str, label: str, icon: str = "", state: str = "") -> str:
    """Render one metric box. `state` ∈ {'', 'alert', 'amber', 'success'}.

    Internal helper for render_model_status_panel. Kept private (leading
    underscore) because it produces a class-prefixed HTML string that
    only makes sense in the context of _MODEL_STATUS_CSS.
    """
    cls = f"ais-metric-box {state}".strip() if state else "ais-metric-box"
    icon_html = f'<span class="ais-metric-label-icon">{icon}</span>' if icon else ""
    return (
        f'<div class="{cls}">'
        f'  <div class="ais-metric-value">{value}</div>'
        f'  <div class="ais-metric-label">{icon_html}{label}</div>'
        f'</div>'
    )


def _ais_card(icon: str, title: str, subtitle: str, metrics_html: str) -> None:
    """Render a single card. Same pattern as admin/dashboard.py's _card()
    but with the .ais- class prefix to avoid CSS collisions."""
    st.markdown(
        f"""
        <div class="ais-card">
          <div class="ais-card-header">
            <div class="ais-card-header-icon">{icon}</div>
            <div class="ais-card-header-text">
              <h3>{title}</h3>
              <p>{subtitle}</p>
            </div>
          </div>
          <div class="ais-card-body">
            <div class="ais-metric-grid">
              {metrics_html}
            </div>
          </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_model_status_panel(summary: dict | None = None) -> None:
    """Render the full Model Status + Self-Learning Loop section.

    Used by:
      • admin/dashboard.py (the only role that should see it by default)
      • ai_insights.py, but ONLY when get_current_role() == "admin"
        (so an admin browsing the AI Insights page still sees the panel)

    Visual design: matches the rest of the admin dashboard — two green
    header cards (Model Status + Self-Learning Loop) each containing a
    flex-wrap grid of metric boxes. The "needs data" / "no data" cells
    are highlighted in amber so the admin can spot training gaps at a
    glance. The CSS is embedded so the function is self-contained.
    """
    if summary is None:
        try:
            summary = get_training_summary()
        except Exception as e:
            st.error(f"Failed to load AI engine: {e}")
            return

    # Inject the card CSS once per render. Browser idempotent: redefining
    # the same <style> block on a rerun is a no-op.
    st.markdown(_MODEL_STATUS_CSS, unsafe_allow_html=True)

    # ── Card 1: Model Status (5 metrics) ────────────────────────────────────
    model_metrics_html = (
        _ais_metric_box(
            f"{summary['orders_count']} orders / {summary['order_items_count']} items",
            "Training Samples",
            "📊",
        )
        + _ais_metric_box(
            str(summary["products_count"]),
            "Products Trained",
            "📦",
        )
        + _ais_metric_box(
            str(summary["demand_models_trained"]),
            "Demand Models",
            "📈",
            state="alert" if summary["demand_models_trained"] == 0 else "success",
        )
        + _ais_metric_box(
            f"{summary.get('price_model_r2', 0):.2f}",
            "Price Model R²",
            "💰",
            state="amber" if not summary.get("price_model_trained") else "success",
        )
        + _ais_metric_box(
            f"{summary.get('recommender_interactions', 0)} interactions",
            "Recommender",
            "🎯",
            state="amber" if not summary.get("recommender_trained") else "success",
        )
    )
    _ais_card(
        icon="🧠",
        title="Model Status",
        subtitle="How many models are trained and on how much data",
        metrics_html=model_metrics_html,
    )

    # ── Card 2: Self-Learning Loop (4 metrics) ──────────────────────────────
    scored = summary.get("scored_predictions", 0) or 0
    demand_acc = summary.get("demand_accuracy_pct")
    price_acc = summary.get("price_accuracy_pct")
    loop_metrics_html = (
        _ais_metric_box(
            str(summary.get("total_predictions_logged", 0)),
            "Predictions Logged",
            "📝",
        )
        + _ais_metric_box(
            str(scored),
            "Scored vs Actuals",
            "✅",
            state="amber" if scored == 0 else "success",
        )
        + _ais_metric_box(
            f"{demand_acc:.1f}%" if isinstance(demand_acc, (int, float)) else "—",
            "Demand Accuracy",
            "📈",
            state="amber" if not isinstance(demand_acc, (int, float)) else "success",
        )
        + _ais_metric_box(
            f"{price_acc:.1f}%" if isinstance(price_acc, (int, float)) else "—",
            "Price Accuracy",
            "💰",
            state="amber" if not isinstance(price_acc, (int, float)) else "success",
        )
    )
    _ais_card(
        icon="🔁",
        title="Self-Learning Loop",
        subtitle="How many predictions have been scored against real outcomes",
        metrics_html=loop_metrics_html,
    )

    # ── Caption with timestamps (small, below the cards) ────────────────────
    st.caption(
        "🔄 Models auto-retrain every 5 minutes. Every prediction is logged to "
        "`ai_prediction_log`, and once the truth arrives (an order is placed or a "
        "price is changed) the engine backfills the actual value, computes MAE/MAPE "
        "per product, and uses the learned bias to correct the next prediction. "
        f"Last trained: {summary.get('last_trained', 'unknown')[:19]} · "
        f"Model version: {summary.get('model_version', 'unknown')}"
    )


def render_ai_insights():
    page_header("🤖 AI Insights", "Personalized demand forecasts, price suggestions, and recommendations")

    user = get_current_user()
    if not user:
        return

    # ---- Check if ML libraries are available ----
    try:
        summary = get_training_summary()
    except Exception as e:
        st.error(f"Failed to load AI engine: {e}")
        return

    if not summary.get("ml_available", True):
        st.warning("⚠️ AI features require additional libraries that aren't installed.")
        st.info(
            "**To enable AI Insights:**\n\n"
            "Add these to your `requirements.txt` on Streamlit Cloud:\n"
            "```\npandas\nnumpy\nscikit-learn\n```\n\n"
            "Then reboot the app. The AI features are optional — everything else works without them."
        )
        return

    # Model Status + Self-Learning Loop is admin-only.
    # Producers/merchants/customers get the per-product forecasts below,
    # but the platform-wide internal metrics are no longer shown here.
    if get_current_role() == "admin":
        render_model_status_panel(summary)

    # ---- Sub-tabs ----
    sub_tab1, sub_tab2, sub_tab3 = st.tabs([
        "📈 Demand Forecast",
        "💰 Price Prediction",
        "🎯 Recommendations",
    ])

    with sub_tab1:
        _render_demand_forecast()
    with sub_tab2:
        _render_price_prediction(user_id=user.get("id"))
    with sub_tab3:
        _render_recommendations(user["id"])


def _render_demand_forecast():
    st.markdown("##### 📈 Demand Forecast — Next 30 Days")
    st.caption("Predicts total demand per product over the next 30 days. Pick a product to see its actuals-vs-forecast chart.")

    try:
        forecasts = forecast_all_products(horizon_days=30)
    except Exception as e:
        st.error(f"Failed: {e}")
        return

    if not forecasts:
        st.info("No products to forecast yet.")
        return

    trained = [f for f in forecasts if f.get("method") in ("linear_regression", "gradient_boosting")]
    if not trained:
        st.warning(
            "⚠️ Not enough order history yet to train demand models. "
            "Place a few orders first, then check back — the model retrains every 5 minutes."
        )

    # Save to Supabase (background)
    if trained and st.button("💾 Save predictions to database", key="save_demand"):
        n = save_demand_forecasts_to_supabase(trained)
        st.success(f"Saved {n} demand predictions to ai_predictions table.")

    # ---- Per-product line chart ----
    if trained:
        st.markdown("##### 📊 Per-Product Demand Chart")
        product_options = {f"{f.get('name', '')} ({f.get('sku', '')})": f for f in trained}
        selected_label = st.selectbox(
            "Select a product",
            options=list(product_options.keys()),
            key="demand_product_select",
        )
        selected = product_options.get(selected_label)
        if selected:
            _render_demand_chart(selected)

    # ---- Full table ----
    st.markdown("##### 📋 All Products")
    df = pd.DataFrame([
        {
            "SKU": f.get("sku", ""),
            "Product": f.get("name", ""),
            "Category": f.get("category", ""),
            "Current Stock": f.get("current_stock", 0),
            "Predicted Demand (30d)": f.get("predicted_demand_30d", 0),
            "Avg Daily": f.get("avg_daily_demand", 0),
            "Trend": f.get("trend", ""),
            "Confidence": f"{f.get('confidence', 0) * 100:.0f}%",
            # Look up the accuracy from THIS row's forecast dict, not
            # from the "selected" product — that variable only exists
            # inside the per-product chart branch above and is
            # undefined here when there are no trained forecasts.
            "Accuracy (MAPE)": _format_mape(f.get("accuracy")),
            "Samples": f.get("samples", 0),
            "Method": f.get("method", ""),
        }
        for f in forecasts
    ])
    st.dataframe(df, use_container_width=True, hide_index=True)

    # ---- Restock alerts ----
    st.markdown("##### ⚠️ Restock Alerts")
    alerts = [
        f for f in forecasts
        if f.get("predicted_demand_30d", 0) > f.get("current_stock", 0)
        and f.get("method") in ("linear_regression", "gradient_boosting")
    ]
    if not alerts:
        st.success("All products have sufficient stock for predicted demand.")
    else:
        for a in alerts:
            shortfall = a["predicted_demand_30d"] - a["current_stock"]
            st.warning(
                f"**{a['name']}** ({a['sku']}) — predicted demand {a['predicted_demand_30d']:.0f} "
                f"exceeds stock {a['current_stock']}. Restock by ~{shortfall:.0f} units."
            )


def _render_demand_chart(forecast: dict):
    """Plot actuals vs fitted (history) + forecast (future) for one product.

    Uses st.line_chart with a 3-column DataFrame:
      date | Actual | Fitted | Forecast
    """
    history = forecast.get("history", []) or []
    future = forecast.get("forecast", []) or []

    rows = []
    for h in history:
        rows.append({
            "Date": h["date"],
            "Actual": float(h.get("actual", 0)),
            "Fitted (model)": float(h.get("fitted", 0)) if h.get("fitted") is not None else None,
            "Forecast": None,
        })
    for f in future:
        rows.append({
            "Date": f["date"],
            "Actual": None,
            "Fitted (model)": None,
            "Forecast": float(f.get("predicted", 0)),
        })

    if not rows:
        st.info("No historical data yet for this product — place some orders to see the chart.")
        return

    chart_df = pd.DataFrame(rows).set_index("Date")
    # Convert date strings to datetime so the x-axis is ordered correctly.
    chart_df.index = pd.to_datetime(chart_df.index)
    chart_df = chart_df.sort_index()

    # Stash the description in a small caption row above the chart.
    # We show the per-product accuracy (specific to this product) here
    # because it's the product owner's own data — not platform-wide.
    acc = forecast.get("accuracy")
    cap_parts = [
        f"Trend: **{forecast.get('trend', 'stable')}**",
        f"Predicted 30-day demand: **{forecast.get('predicted_demand_30d', 0):.0f} units**",
        f"Confidence: **{forecast.get('confidence', 0) * 100:.0f}%**",
        f"Method: `{forecast.get('method', '?')}`",
    ]
    if acc:
        mape = acc.get("mape")
        if mape is not None:
            cap_parts.append(f"Your historical accuracy: **{100 - mape:.1f}%** (MAPE {mape:.1f}%)")
        cap_parts.append(f"Samples scored: **{acc.get('samples', 0)}**")
    # v7: surface a fallback warning so users know when the chart shows a
    # flat average instead of a real learned forecast.
    if forecast.get("model_status") and forecast["model_status"] != "ok":
        st.warning(
            "⚠️ **AI in fallback mode** — not enough order history to train a "
            "real forecast yet. The chart shows the historical daily average "
            "as a flat line. Place more orders to unlock the real prediction."
        )
    st.caption(" · ".join(cap_parts))

    st.line_chart(chart_df, use_container_width=True, height=320)


def _render_price_prediction(user_id: str | None = None):
    """Render the price prediction tab.

    The platform-wide MAPE bar chart ("Price Accuracy Across All Products")
    is admin-only — it shows accuracy for products the current user doesn't
    own and is operational info. Per-product accuracy (in the chart caption
    and table) is kept for everyone.
    """
    st.markdown("##### 💰 Price Optimization")
    st.caption("Suggests optimal prices based on stock levels, category, and sales velocity. Pick a product to see its predicted-vs-actual price history.")

    try:
        predictions = predict_optimal_prices()
    except Exception as e:
        st.error(f"Failed: {e}")
        return

    if not predictions:
        st.info("Not enough product data to train the price model yet.")
        return

    if st.button("💾 Save predictions to database", key="save_prices"):
        n = save_price_predictions_to_supabase(predictions)
        st.success(f"Saved {n} price predictions.")

    # ---- Per-product chart ----
    st.markdown("##### 📊 Per-Product Price Chart")
    product_options = {f"{p['name']} ({p['sku']})": p for p in predictions}
    selected_label = st.selectbox(
        "Select a product",
        options=list(product_options.keys()),
        key="price_product_select",
    )
    selected_p = product_options.get(selected_label)
    if selected_p:
        _render_price_chart(selected_p)

    # ---- MAPE bar chart across all products (ADMIN ONLY) ----
    # This shows platform-wide accuracy. Regular users only see their
    # own product's accuracy in the per-product chart above.
    if get_current_role() == "admin":
        st.markdown("##### 📉 Price Accuracy Across All Products (MAPE %, lower is better)")
        mape_rows = []
        for p in predictions:
            acc = p.get("accuracy")
            mape = (acc or {}).get("mape")
            if mape is not None:
                mape_rows.append({"Product": p["name"], "MAPE %": float(mape)})
        if mape_rows:
            mape_df = pd.DataFrame(mape_rows).set_index("Product")
            st.bar_chart(mape_df, use_container_width=True, height=280)
        else:
            st.info("No scored price predictions yet. As producers change prices in response to recommendations, accuracy will appear here.")

    # ---- Full table ----
    st.markdown("##### 📋 All Products")
    df = pd.DataFrame([
        {
            "SKU": p["sku"],
            "Product": p["name"],
            "Current Price": format_currency(p["current_price"]),
            "Predicted Price": format_currency(p["predicted_price"]),
            "Difference": format_currency(p["difference"]),
            "% Change": f"{p['pct_change']:+.1f}%",
            "Recommendation": p["recommendation"].upper(),
            "Confidence": f"{p['confidence'] * 100:.0f}%",
            "Accuracy (MAPE)": _format_mape(p.get("accuracy")),
        }
        for p in predictions
    ])
    st.dataframe(df, use_container_width=True, hide_index=True)

    # ---- Summary ----
    st.markdown("##### 💡 Quick Recommendations")
    increase = [p for p in predictions if p["recommendation"] == "increase"]
    decrease = [p for p in predictions if p["recommendation"] == "decrease"]
    hold = [p for p in predictions if p["recommendation"] == "hold"]

    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("📈 Increase Price", len(increase))
    with col2:
        st.metric("📉 Decrease Price", len(decrease))
    with col3:
        st.metric("➡️ Hold Price", len(hold))


def _render_price_chart(prediction: dict):
    """Plot predicted vs actual price over time for one product.

    Uses st.line_chart with a 3-column DataFrame:
      date | Predicted | Actual
    """
    history = prediction.get("history", []) or []
    if not history:
        st.info("No scored price predictions yet for this product. Once the producer changes the price, the actual line will appear here.")
        return

    rows = []
    for h in history:
        rows.append({
            "Date": h.get("predicted_at", ""),
            "Predicted (Br)": h.get("predicted"),
            "Actual (Br)": h.get("actual"),
        })

    chart_df = pd.DataFrame(rows).set_index("Date")
    chart_df.index = pd.to_datetime(chart_df.index, errors="coerce")
    chart_df = chart_df.sort_index()

    # Per-product accuracy is shown to everyone — it's the user's own product.
    cap_parts = [
        f"Current price: **{format_currency(prediction['current_price'])}**",
        f"Predicted optimal: **{format_currency(prediction['predicted_price'])}**",
        f"Recommendation: **{prediction['recommendation'].upper()}** ({prediction['pct_change']:+.1f}%)",
        f"Bias correction applied: **{prediction.get('bias', 0):.2f}**",
    ]
    acc = prediction.get("accuracy")
    if acc:
        mape = acc.get("mape")
        if mape is not None:
            cap_parts.append(f"Your accuracy: **{100 - mape:.1f}%** (MAPE {mape:.1f}%)")
        cap_parts.append(f"Samples scored: **{acc.get('samples', 0)}**")
    # v7: surface a fallback warning when the recommendation came from the
    # flat baseline (no real learned signal available).
    if prediction.get("model_status") and prediction["model_status"] != "ok":
        st.warning(
            "⚠️ **AI in fallback mode** — not enough sales history to compute a "
            "demand signal. The recommendation is a safe bounded nudge from the "
            "current price (±15% max). Add sales data to unlock the real model."
        )
    st.caption(" · ".join(cap_parts))

    st.line_chart(chart_df, use_container_width=True, height=320)


def _render_recommendations(user_id: str):
    st.markdown("##### 🎯 Personalized Recommendations")
    st.caption("Collaborative filtering — suggests products based on what similar users order/favorite.")

    try:
        recs = get_recommendations(user_id, top_n=6)
    except Exception as e:
        st.error(f"Failed: {e}")
        return

    if not recs:
        st.info("No recommendations available yet.")
        return

    method_label = {
        "collaborative_filtering": "🎯 Based on users with similar taste",
        "popularity_based": "🔥 Most popular products",
        "fallback_random": "✨ Try these products",
    }.get(recs[0].get("method", ""), "Recommended")

    st.info(method_label)

    cols = st.columns(3)
    for i, r in enumerate(recs):
        with cols[i % 3]:
            with st.container(border=True):
                if r.get("image_url"):
                    try:
                        st.image(r["image_url"], use_container_width=True)
                    except Exception:
                        st.markdown("📦")
                else:
                    # Native Streamlit placeholder — no HTML.
                    st.container(height=120, border=True).markdown(
                        "📦\n\n*No image*"
                    )
                st.markdown(f"**{r['name']}**")
                st.caption(f"{r.get('category', '')}")
                st.markdown(f"**{format_currency(r['price'])}**")
                st.caption(f"Stock: {r.get('stock', 0)}")


def _format_mape(acc) -> str:
    """Format an accuracy dict as a human-readable MAPE cell."""
    if not acc:
        return "—"
    mape = acc.get("mape")
    if mape is None:
        return "—"
    return f"{mape:.1f}%"
