"""
AI Insights — the AI tab visible to all roles.

Three sub-tabs:
  • 📈 Demand Forecast  — predicts next 30-day demand per product
  • 💰 Price Prediction  — suggests optimal prices per product
  • 🎯 Recommendations  — suggests products to buy/stock

All predictions are generated by self-learning models that retrain every 5
minutes from the latest Supabase data. As more orders/products accumulate,
predictions naturally improve.
"""
from __future__ import annotations

import streamlit as st
import pandas as pd

from auth.session import get_current_user, get_current_role
from utils.ui import page_header, metric_card
from utils.helpers import format_currency
from ai.engine import get_training_summary, MLEngine
from ai.price_prediction import predict_optimal_prices, save_price_predictions_to_supabase
from ai.demand_forecast import forecast_all_products, save_demand_forecasts_to_supabase
from ai.recommendations import get_recommendations


def render_ai_insights():
    page_header("🤖 AI Insights", "Self-learning predictions trained live on your Supabase data")

    user = get_current_user()
    if not user:
        return

    # ---- Check if ML libraries are available ----
    try:
        summary = get_training_summary()
    except Exception as e:
        st.error(f"Failed to load AI engine: {e}")
        return

    if not summary.get("ml_available", True):
        st.warning("⚠️ AI features require additional libraries that aren't installed.")
        st.info(
            "**To enable AI Insights:**\n\n"
            "Add these to your `requirements.txt` on Streamlit Cloud:\n"
            "```\npandas\nnumpy\nscikit-learn\n```\n\n"
            "Then reboot the app. The AI features are optional — everything else works without them."
        )
        return

    _render_model_status(summary)

    # ---- Sub-tabs ----
    sub_tab1, sub_tab2, sub_tab3 = st.tabs([
        "📈 Demand Forecast",
        "💰 Price Prediction",
        "🎯 Recommendations",
    ])

    with sub_tab1:
        _render_demand_forecast()
    with sub_tab2:
        _render_price_prediction()
    with sub_tab3:
        _render_recommendations(user["id"])


def _render_model_status(summary: dict):
    """Show the training data + model metrics — proof the engine is self-learning."""
    st.markdown("##### 🧠 Model Status")
    col1, col2, col3, col4, col5 = st.columns(5)
    with col1:
        metric_card("Training Samples", f"{summary['orders_count']} orders / {summary['order_items_count']} items")
    with col2:
        metric_card("Products Trained", str(summary["products_count"]))
    with col3:
        metric_card("Demand Models", str(summary["demand_models_trained"]))
    with col4:
        r2 = summary.get("price_model_r2", 0)
        metric_card(
            "Price Model R²",
            f"{r2:.2f}",
            delta="✅ trained" if summary.get("price_model_trained") else "❌ no data",
        )
    with col5:
        metric_card(
            "Recommender",
            f"{summary.get('recommender_interactions', 0)} interactions",
            delta="✅ ready" if summary.get("recommender_trained") else "⚠️ needs data",
        )

    st.caption(
        "🔄 Models auto-retrain every 5 minutes from your latest Supabase data. "
        "As more orders come in, predictions become more accurate — this is the self-learning loop. "
        f"Last trained: {summary.get('last_trained', 'unknown')[:19]}"
    )
    st.markdown("---")


def _render_demand_forecast():
    st.markdown("##### 📈 Demand Forecast — Next 30 Days")
    st.caption("Predicts total demand per product over the next 30 days, based on historical order patterns.")

    try:
        forecasts = forecast_all_products(horizon_days=30)
    except Exception as e:
        st.error(f"Failed: {e}")
        return

    if not forecasts:
        st.info("No products to forecast yet.")
        return

    trained = [f for f in forecasts if f.get("method") == "linear_regression"]
    if not trained:
        st.warning(
            "⚠️ Not enough order history yet to train demand models. "
            "Place a few orders first, then check back — the model retrains every 5 minutes."
        )

    # Save to Supabase (background)
    if trained and st.button("💾 Save predictions to database", key="save_demand"):
        n = save_demand_forecasts_to_supabase(trained)
        st.success(f"Saved {n} demand predictions to ai_predictions table.")

    df = pd.DataFrame([
        {
            "SKU": f.get("sku", ""),
            "Product": f.get("name", ""),
            "Category": f.get("category", ""),
            "Current Stock": f.get("current_stock", 0),
            "Predicted Demand (30d)": f.get("predicted_demand_30d", 0),
            "Avg Daily": f.get("avg_daily_demand", 0),
            "Trend": f.get("trend", ""),
            "Confidence": f"{f.get('confidence', 0) * 100:.0f}%",
            "Samples": f.get("samples", 0),
            "Method": f.get("method", ""),
        }
        for f in forecasts
    ])
    st.dataframe(df, use_container_width=True, hide_index=True)

    # Highlight restock alerts
    st.markdown("##### ⚠️ Restock Alerts")
    alerts = [
        f for f in forecasts
        if f.get("predicted_demand_30d", 0) > f.get("current_stock", 0)
        and f.get("method") == "linear_regression"
    ]
    if not alerts:
        st.success("All products have sufficient stock for predicted demand.")
    else:
        for a in alerts:
            shortfall = a["predicted_demand_30d"] - a["current_stock"]
            st.warning(
                f"**{a['name']}** ({a['sku']}) — predicted demand {a['predicted_demand_30d']:.0f} "
                f"exceeds stock {a['current_stock']}. Restock by ~{shortfall:.0f} units."
            )


def _render_price_prediction():
    st.markdown("##### 💰 Price Optimization")
    st.caption("Suggests optimal prices based on stock levels, category, and sales velocity.")

    try:
        predictions = predict_optimal_prices()
    except Exception as e:
        st.error(f"Failed: {e}")
        return

    if not predictions:
        st.info("Not enough product data to train the price model yet.")
        return

    if st.button("💾 Save predictions to database", key="save_prices"):
        n = save_price_predictions_to_supabase(predictions)
        st.success(f"Saved {n} price predictions.")

    df = pd.DataFrame([
        {
            "SKU": p["sku"],
            "Product": p["name"],
            "Current Price": format_currency(p["current_price"]),
            "Predicted Price": format_currency(p["predicted_price"]),
            "Difference": format_currency(p["difference"]),
            "% Change": f"{p['pct_change']:+.1f}%",
            "Recommendation": p["recommendation"].upper(),
            "Confidence": f"{p['confidence'] * 100:.0f}%",
        }
        for p in predictions
    ])
    st.dataframe(df, use_container_width=True, hide_index=True)

    # Summary recommendations
    st.markdown("##### 💡 Quick Recommendations")
    increase = [p for p in predictions if p["recommendation"] == "increase"]
    decrease = [p for p in predictions if p["recommendation"] == "decrease"]
    hold = [p for p in predictions if p["recommendation"] == "hold"]

    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("📈 Increase Price", len(increase))
    with col2:
        st.metric("📉 Decrease Price", len(decrease))
    with col3:
        st.metric("➡️ Hold Price", len(hold))


def _render_recommendations(user_id: str):
    st.markdown("##### 🎯 Personalized Recommendations")
    st.caption("Collaborative filtering — suggests products based on what similar users order/favorite.")

    try:
        recs = get_recommendations(user_id, top_n=6)
    except Exception as e:
        st.error(f"Failed: {e}")
        return

    if not recs:
        st.info("No recommendations available yet.")
        return

    method_label = {
        "collaborative_filtering": "🎯 Based on users with similar taste",
        "popularity_based": "🔥 Most popular products",
        "fallback_random": "✨ Try these products",
    }.get(recs[0].get("method", ""), "Recommended")

    st.info(method_label)

    cols = st.columns(3)
    for i, r in enumerate(recs):
        with cols[i % 3]:
            with st.container(border=True):
                if r.get("image_url"):
                    try:
                        st.image(r["image_url"], use_container_width=True)
                    except Exception:
                        st.markdown("📦")
                else:
                    st.markdown(
                        "<div style='height:120px; background:#f1f5f9; border-radius:8px; "
                        "display:flex; align-items:center; justify-content:center; "
                        "font-size:2.5rem; color:#94a3b8;'>📦</div>",
                        unsafe_allow_html=True,
                    )
                st.markdown(f"**{r['name']}**")
                st.caption(f"{r.get('category', '')}")
                st.markdown(f"**{format_currency(r['price'])}**")
                st.caption(f"Stock: {r.get('stock', 0)}")
